# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
      - unixodbc-dev
      - virtuoso-opensource
      - virtuoso-server

after_success:
    - Rscript -e 'covr::codecov()'
